export const DOCUMENT_INSERT = 'DOCUMENT_INSERT';
export const DOCUMENT_UPDATE = 'DOCUMENT_UPDATE';
export const DOCUMENT_REMOVE = 'DOCUMENT_REMOVE';
export const DOCUMENT_COUNT_SET = 'DOCUMENT_COUNT_SET';
